server:
  port: 9525
spring:
  application:
    name: gateway
  profiles:
    active: zookeeper
  cloud:
    gateway:
      routes:
        - id: gateway_routes1
          uri: lb://order80
          predicates:
            - Path=/purduct/*



