server:
  port: 8002
spring:
  application:
    name: purduct
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud_db01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    #password: 123456
    password: root
  profiles:
    active: zookeeper
mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.mayaoting.springcloud.entities
